security:
    oauth2:
        client:
            clientId: 0c0dacc7ebc7445182168b5bf57b0dd4
            clientSecret: d03fab2cd4f8441ab81ee632bf1c38a1
            accessTokenUri: https://api.instagram.com/oauth/access_token
            userAuthorizationUri: https://api.instagram.com/oauth/authorize
            clientAuthenticationScheme: form
            scope: public_content
            authenticationScheme: query
        resource:
            userInfoUri: https://api.instagram.com/v1/users/self


# DataSource settings: set here your own configurations for the database
# connection. In this example we have "netgloo_blog" as database name and
# "root" as username and password.
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/eventure
    username: root
    password: root
    testWhileIdle: true
    validationQuery: SELECT 1

# Show or not log for each sql query
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
      naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect