security:
    oauth2:
        client:
            clientId: 0c0dacc7ebc7445182168b5bf57b0dd4
            clientSecret: d03fab2cd4f8441ab81ee632bf1c38a1
            accessTokenUri: https://api.instagram.com/oauth/access_token
            userAuthorizationUri: https://api.instagram.com/oauth/authorize
            clientAuthenticationScheme: form
            scope: public_content
            authenticationScheme: query
        resource:
            userInfoUri: https://api.instagram.com/v1/users/self