security:
    oauth2:
        client:
            clientId: 0c0dacc7ebc7445182168b5bf57b0dd4
            clientSecret: d03fab2cd4f8441ab81ee632bf1c38a1
            accessTokenUri: https://api.instagram.com/oauth/access_token
            userAuthorizationUri: https://api.instagram.com/oauth/authorize
            clientAuthenticationScheme: form
            scope: public_content
            authenticationScheme: query
        resource:
            userInfoUri: https://api.instagram.com/v1/users/self

spring:
  datasource:
    url: ${JDBC_DATABASE_URL}
    username: rxjgvggtywqrdx
    password: 3aKQbRlbd5_fqvZCekTZZ5HtBH
    testWhileIdle: true
    validationQuery: SELECT 1
    driverClassName: org.postgresql.Driver

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
      naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL82Dialect